#!/bin/sh

# A hook script to run Xcode unit tests before committing.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

SCHEME1="Al-Najd"
SCHEME2="Dashboard"
SCHEME3="Calendar"
SCHEME4="Schedule"

SDK="iphonesimulator"
 
TASK1=`xcodebuild \
  -project Al\ Najd.xcodeproj \
  -scheme $SCHEME1 \
  -sdk $SDK \
  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
  test
  `
TASK2=`xcodebuild \
  -project Al\ Najd.xcodeproj \
  -scheme $SCHEME2 \
  -sdk $SDK \
  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
  test
  `
TASK3=`xcodebuild \
  -project Al\ Najd.xcodeproj \
  -scheme $SCHEME3 \
  -sdk $SDK \
  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
  test
  `
TASK4=`xcodebuild \
  -project Al\ Najd.xcodeproj \
  -scheme $SCHEME4 \
  -sdk $SDK \
  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
  test
  `

# xcpretty makes output nicer
if hash xcpretty 2>/dev/null; then
    TASK1 | xcpretty -t
    TASK2 | xcpretty -t
    TASK3 | xcpretty -t
    TASK4 | xcpretty -t
else
    TASK1
    TASK2
    TASK3
    TASK4
fi