require 'json'
require 'fileutils'
require 'io/console'



def input(placeholder)
    print "#{placeholder}: "
    return gets.chomp
end

def secure_input(placeholder)
    print "#{placeholder}: "
    return STDIN.noecho(&:gets).chomp
end

puts("Great!, now we're going to setup fastlane for you")
# Steps
# 0. Check if .env.secret Exists, if yes, skip till # 5.
# 1. Get current user's account
# 2. Get the passphrase that is used to store the match repo
# 3. Get ID of your Developer Portal Team (denoted by team_id)
# 4. Get ID of your iTunes Connect team (denoted by itc_team_id)
# 5. Generate .env.secret
# 6. Add it to .gitignore

# 0. Check if .env.secret Exists, if yes, skip till # 5.
if File.file?("./fastlane/.env.secret")
    puts("👍 .env.secret already exists, skipping to step # 5")
else

    # 1. Get current user's account
    puts("As of now, we are only using Fastlane, so we will be needing the following...")
    puts("1. AppleID")
    puts("2. Apple Password")
    puts("We will be using Fastlane's Credential Manager for this (uses the Keychain to store them)")

    apple_id = input("Please enter your Apple ID")

    puts("Now we will need your Apple ID's password")
    puts("Don't worry, it's stored in the Keychain, and Fastlane is the one storing it so it can safely use it")

    system("fastlane fastlane-credentials add --username #{apple_id}")

    # 2. Get the passphrase that is used to store the match repo
    puts("Alright, now to match you!, we need to have you invited over Keeper for us to share with you Fastlane's Passwords")
    puts("To get this, we will need to do the following...")
    puts("1. Ping Imran or Mudassir (IT or DevOps) to give you access to Keeper")
    puts("2. Ping any of the iOS memebers to give you to the credentials for fastlane folder")
    puts("3. You will be looking for the field called 'Fastlane Secrets'")
    puts("4. Copy the value beside 'Match Git Repository Decryption Password' and paste it here")
    match_repo_passphrase = secure_input("Now, what's the secret word? (MATCH_PASSWORD)")

    # 3. Get App Specific Password
    puts("Now, we need to get app specific password so u don't get spammed with OTPs for 2FA whenever u need to deal with the appstore")
    puts("First, go to: https://appleid.apple.com/account/manage/section/security")
    puts("Then, select App-Specific Passwords")
    puts("Then type whatever nickname you want, then copy and paste it here")

    app_specific_password = secure_input("Once you've it, please input it here (FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD)")

    # 4. Get Fastlane_Session Cookie via 'fastlane spaceauth -u <apple_id>'
    puts("Now, we need to get the Fastlane_Session cookie")
    puts("We will run fastlane spaceauth for you, and you will need to login to your Apple ID")
    puts("Once you've logged in, copy the cookie and paste it here")
    puts("To not lose the progress of this script, open a new tab in the terminal by pressing CMD + T and run the following command")
    puts("fastlane spaceauth -u #{apple_id}")
    puts("Once you've copied the cookie, press enter to continue")

    cookie = input("Please paste the cookie here (FASTLANE_SESSION)")



    # 3. Generate .env.secret using the above values 
    puts("Generating .env.secret at ./fastlane/.env.secret")

    File.write('./fastlane/.env.secret', 
    """
# This file is generated by the setup-fastlane.rb script
# DO NOT EDIT THIS FILE
# If you need to change any of the values, please edit the setup-fastlane.rb script
# and run it again

FASTLANE_USER = \"#{apple_id}\"
MATCH_USER = \"#{apple_id}\"
PILOT_USER = \"#{apple_id}\"
PEM_USER = \"#{apple_id}\"
APPLE_ID = \"#{apple_id}\"
MATCH_PASSWORD = \"#{match_repo_passphrase}\"
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = \"#{app_specific_password}\"
FASTLANE_SESSION = \"#{cookie}\"
    """
    )
end

# 6. Check if .env.secret is already added to .gitignore
puts("Checking if .env.secret is already added to .gitignore")

gitignore = File.read('.gitignore')
if !gitignore.include?("fastlane/.env.secret")
    puts("Adding fastlane/.env.secret to .gitignore")
    File.write('.gitignore', "#{gitignore}\n fastlane/.env.secret")
else 
    puts("fastlane/.env.secret is already added to .gitignore")
end

# Print pass for created LocalConfigs
puts("Here's the .env.secret that was created for you")
system("cat ./fastlane/.env.secret")

puts("All done! Now when you run fastlane, it will use the .env.secret file to get the values")
puts("This will save you time when you're running fastlane commands")

puts("Now for the fun part, running fastlane onboard")
system("fastlane onboard")

puts("Enjoy!")